# <% load "#{File.dirname(__FILE__)}/test/kitchen_proxy.rb" %>
driver:
  name: proxy
  host: 127.0.0.1
  reset_command: "exit 0"
  port: 22
  username: vagrant
  password: vagrant
provisioner:
  require_chef_omnibus: false
  chef_solo_path: /usr/local/bin/chef-solo
  script: bootstrap.sh
platforms:
  - name: centos-7.2
    chef_client:
        config:
          http_proxy: http://httpproxy.com
          https_proxy: http://httpsproxy.com
suites:
  - name: add
    run_list:
    attributes: